name: Main_Workflow
on: [push]

jobs:
  package_tested:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        id: run_tests
        run: composer run tester

  notification:
    runs-on: ubuntu-latest
    name: Send SMS after push
    environment: bulkgate_api
    needs: [package_tested]
    if: always() && (needs.package_tested.result == 'failure')
    steps:
      - name: Send SMS after push
        uses: BulkGate/github-actions@master
        id: SendSMS
        with:
          application_id: ${{ secrets.application_id }}
          application_token: ${{ secrets.application_token }}
          number: "420777777777"
          text: "Committed by ${{ github.actor }} - ${{ github.server_url }}/${{ github.repository }}/actions"
          sender_id: "gText"
          sender_id_value: "Github test"
          channel: '{
            "viber": {
              "sender": "BulkGate",
              "expiration": 100,
              "text": "Committed by ${{ github.actor }} - ${{ github.server_url }}/${{ github.repository }}/actions"
            },
            "sms": {
              "sender_id": "gText",
              "sender_id_value": "Lt-Hagan",
              "unicode": true,
              "flash": true,
              "text": "Committed by ${{ github.actor }} - ${{ github.server_url }}/${{ github.repository }}/actions"
            }
          }'

      - name: Get http response
        run: echo "Response is ${{ steps.SendSMS.outputs.response }}"
