name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  url:  # id of input
    description: 'url'
    required: true
    default: 'https://portal.bulkgate.com'
  method:
    description: 'http method'
    required: true
    default: 'POST'
  contentType:
    description: 'contentType'
    required: true
    default: 'application/json'
  application_id:
      description: 'application id'
      required: true
      default: ''
  application_token:
    description: 'application token'
    required: true
    default: ''
outputs:
  response: # response of http request
    description: 'Response of http request'
runs:
  using: 'node12'
  main: 'dist/index.js'