name: Main_Workflow
on: [push]

jobs:
  notification:
    runs-on: ubuntu-latest
    name: Send SMS after push
    environment: bulkgate_api
    env:
      application_id: ${{ secrets.application_id }}
      application_token: ${{ secrets.application_token }}
    steps:
      - name: Send SMS after push
        uses: BulkGate/github-actions@master
        id: SendSMS
        with:
          application_id: ${{ env.application_id }}
          application_token: ${{ env.application_token }}
          number: "420777777777"
          text: "test"
          sender_id: "gText"
          sender_id_value: "Github test"

      - name: Get http response
        run: echo "Response is ${{ steps.SendSMS.outputs.response }}"