name: Main_Workflow
on: [push] #pull_request

jobs:
  package_tested:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        #run: composer run tester
        id: run_tests
        run: ::set-output name=mix-test::$(composer run tester)


  notification:
    runs-on: ubuntu-latest
    name: Send SMS after push
    environment: bulkgate_api
    needs: [package_tested]
    if: always() && (needs.package_tested.result == 'failure')
    env:
      application_id: ${{ secrets.application_id }}
      application_token: ${{ secrets.application_token }}
    steps:
      - name: Send SMS after push
        uses: BulkGate/github-actions@master
        id: SendSMS
        with:
          application_id: ${{ env.application_id }}
          application_token: ${{ env.application_token }}
          number: "420777777777"
          text: 'test'
          sender_id: "gText"
          sender_id_value: "Github test"

      # Use the output from the `SendSMS` step
      - name: Get http response
        run: echo "Response is ${{ steps.SendSMS.outputs.response }}"
      - name: Get http response
        run: echo "Tests output is ${{join(steps.run_tests.outputs.*, '\n')}}"

