name: Report
on:
  workflow_run:
    workflows: ["Main_Workflow"]
    branches: [master]
    types:
      - completed
jobs:
  on-success:
    runs-on: ubuntu-latest
    name: Report tests
    environment: bulkgate_api
    env:
      application_id: ${{ secrets.application_id }}
      application_token: ${{ secrets.application_token }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: "Report success"
        uses: BulkGate/github-actions@master
        with:
          application_id: ${{ env.application_id }}
          application_token: ${{ env.application_token }}
          number: ${{ secrets.phone_number_report }}
          text: ${{ github.event.workflow_run }}
          sender_id: "gText"
          sender_id_value: "BulkGate tester"
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: "Report failure"
        uses: BulkGate/github-actions@master
        with:
          application_id: ${{ env.application_id }}
          application_token: ${{ env.application_token }}
          number: ${{ secrets.phone_number_report }}
          text: 'Test report failure'
          sender_id: "gText"
          sender_id_value: "BulkGate tester"
